### PR TITLE
Improve reporting of parse errors on query / path parameters (no name…

### PR DESCRIPTION
**Pull request by clementdenis**
… available)

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)

### CODE REVIEW

**Review by llbrt — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 382 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/49#-LuaxjgzDLqs0FMHd60w:-Luaxjh-3OZglZOpeexW:b-yf1pmv) ([raw file](https://github.com/aodocs/endpoints-java/blob/32516a19623d281f4822b85d1234245d0886f69a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L382)):*
> ```Java
>   BadRequestException translateJsonException(MismatchedInputException e) {
>     String reason = "parseError";
>     String message = "Parse error for ";
> ```

`message` could be a StringBuilder

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49#-:-LubKDPz-1ApkH0x5Cd9:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by clementdenis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)* status: all files reviewed, 1 unresolved discussion (waiting on @llbrt)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 382 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/49#-LuaxjgzDLqs0FMHd60w:-Luc5wPg9Kw5UquEkqEf:b4bady9) ([raw file](https://github.com/aodocs/endpoints-java/blob/32516a19623d281f4822b85d1234245d0886f69a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L382)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

`message` could be a StringBuilder
</blockquote></details>

I refactored further

**Review by alarribeau — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)* status: all files reviewed, 1 unresolved discussion (waiting on @llbrt)

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/49)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
