### PR TITLE
Support for pattern/min/max in Discovery and Swagger

### PR DESCRIPTION
**Pull request by alarribeau**
Fills pattern/minimum/maximum attributes in both Discovery and Swagger description formats from javax.validation.constraints enums (Pattern, Min, Max, DecimalMin, DecimalMax).

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60)

### CODE REVIEW

**Review by clementdenis — CHANGES_REQUESTED** [review]
Can you update the UNSUPPORTED_FEATURES.md files?
https://github.com/AODocs/endpoints-java/blob/master/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/UNSUPPORTED_FEATURES.md
https://github.com/AODocs/endpoints-java/blob/master/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/UNSUPPORTED_FEATURES.md

Also, you could use the @Size annotations to fill minLength/maxLength for Strings, and minItems/maxItems for Collections / Maps in Swagger specs (I did not find other easy validations that have a match in the spec)

> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60#-:-Mnatw97DhOc2lhgCjaH:b-ght6wk)* status: all files reviewed, 4 unresolved discussions (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 393 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnaoJYfAVV_qDm2-PTK:-MnaoJYfAVV_qDm2-PTL:b-wkpkj4) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L393)):*
> ```Java
>   }
> 
>   private void readMethodRequestParameter(ApiMethodConfig methodConfig, Annotation parameterName,
> ```

That's a LOT of parameters :-)
Shouldn't we introduce a parameter object for all the Annotation objects?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 438 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapPul02Rt20nFqiKQ:-MnapPul02Rt20nFqiKR:blmyht4) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L438)):*
> ```Java
>     ApiParameterConfig parameterConfig =
>         methodConfig.addParameter(parameterNameString, descriptionString, nullable != null, 
>             defaultValueString, type, patternString, boundaries);
> ```

It's a bit weird patternString is not included in the parameter object for numerical bounds.
Why don't you create a ApiParameterValidations object instead?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java, line 5 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapG5cCa7pmClSs3Gm:-MnapG5cCa7pmClSs3Gn:byw8wqm) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java#L5)):*
> ```Java
> import java.util.Objects;
> 
> public class ApiParameterBoundaries {
> ```

When working with numbers, bound is probably better than boundary

https://en.wikipedia.org/wiki/Upper_and_lower_bounds

=> So ApiParameterBounds
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java, line 424 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-Mnar0W56GO0MFv9fCvR:-Mnar0W56GO0MFv9fCvS:buuiagj) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java#L424)):*
> ```Java
>         schema.setMaximum(parameterConfig.getBoundaries().getMax().toString());
>       }
>     }
> ```

The block could be shorter (and avoid repetitions) like this:

    ApiParameterBoundaries boundaries = parameterConfig.getBoundaries();
    if (boundaries != null) {
      Stream.of(boundaries.getDecimalMin(), boundaries.getMin())
              .findFirst().map(Objects::toString).ifPresent(schema::setMinimum);
      Stream.of(boundaries.getDecimalMax(), boundaries.getMax())
              .findFirst().map(Objects::toString).ifPresent(schema::setMaximum);
    }

Also, maybe a comment on how decimal bounds take precedence over integer ones?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 485 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnarVTM0QB3uWinJEGl:-MnarVTM0QB3uWinJEGm:b-qx91fg) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L485)):*
> ```Java
>           }
>           String pattern = parameterConfig.getPattern();
>           if (!Strings.isEmptyOrWhitespace(pattern)) {
> ```

Not related to your code as it's done like that for defaultValue, but it's weird the condition is different than in the DiscoveryGenerator (non-null vs !isEmptyOrWhitespace)
=> shouldn't this be uniform?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 500 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnatR2p1P6SEd4sK3Vn:-MnatR2p1P6SEd4sK3Vo:bx9y0ws) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L500)):*
> ```Java
>             } else if (parameterConfig.getBoundaries().getMax() != null) {
>               parameter.setMaximum(new BigDecimal(parameterConfig.getBoundaries().getMax()));
>             }
> ```

You can probably do something a bit nicer here too with Streams/Optionals, but it's a bit tricker
At least you can extract parameterConfig.getBoundaries() as a variable :-) (11 occurrences!!)

**Review by alarribeau — COMMENTED** [review]
I considered them but I don't find them very useful in practice so I decided to start with the useful ones in this PR.

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60#-:-Mne3gcD2QbiLzbHU0Cc:bx2b74s)* status: all files reviewed, 5 unresolved discussions (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 393 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnaoJYfAVV_qDm2-PTK:-Mne1J0Q95SC_baO1CVM:bnldjbs) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L393)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

That's a LOT of parameters :-)
Shouldn't we introduce a parameter object for all the Annotation objects?
</blockquote></details>

For sure that's a lot of parameters :)
I considered it but I was reluctant to alter significantly the method signature in case we want to keep in sync with the original repo. 
If you think it's ok, I can definitely introduce it.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 438 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapPul02Rt20nFqiKQ:-Mne31yX5hzwEMcU7b7T:b7l5elh) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L438)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

It's a bit weird patternString is not included in the parameter object for numerical bounds.
Why don't you create a ApiParameterValidations object instead?
</blockquote></details>

Ok, I will.  It will make it easier to add new validations like the one you suggested
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java, line 5 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapG5cCa7pmClSs3Gm:-Mne4dAc2dTSNpEEaVRd:bv0z9ch) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java#L5)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

When working with numbers, bound is probably better than boundary

https://en.wikipedia.org/wiki/Upper_and_lower_bounds

=> So ApiParameterBounds
</blockquote></details>

=> ApiParameterValidations
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 485 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnarVTM0QB3uWinJEGl:-Mne4jbr2pKEwXzFPI8E:bmnv939) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L485)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Not related to your code as it's done like that for defaultValue, but it's weird the condition is different than in the DiscoveryGenerator (non-null vs !isEmptyOrWhitespace)
=> shouldn't this be uniform?
</blockquote></details>

Here again I was hesitant between keeping the codebase inline with the main repo or aligning all the checks (defaultValue too) between both generators....

**Review by clementdenis — COMMENTED** [review]
String size is actually a pretty common use case (we have some in our API, like the comments, ...).
I can't think of arrays with size limits in our API, but we probably should have some to avoid performance issues ;)

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60#-:-Mne8VJr-Y5xUrrnmsQp:b-26sotd)* status: all files reviewed, 5 unresolved discussions (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 393 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnaoJYfAVV_qDm2-PTK:-Mne80iBApyPswP9Wh8k:b-5i3q4) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L393)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

For sure that's a lot of parameters :)
I considered it but I was reluctant to alter significantly the method signature in case we want to keep in sync with the original repo. 
If you think it's ok, I can definitely introduce it.
</blockquote></details>

The original repo did not get any update in years ... I think we can safely diverge from it now :)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 485 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnarVTM0QB3uWinJEGl:-Mne8Iwp3F_NQ6HSSNmn:bpa30mb) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L485)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Here again I was hesitant between keeping the codebase inline with the main repo or aligning all the checks (defaultValue too) between both generators....
</blockquote></details>

OK, let's keep it this way for now, it's only for very corner cases anyway.

**Review by alarribeau — COMMENTED** [review]
Ok, I'll start another PR once this one get merged !

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60#-:-MneTJ8iE6UydDYEZAzQ:bvcwdgq)* status: 6 of 19 files reviewed, 4 unresolved discussions (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 393 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnaoJYfAVV_qDm2-PTK:-MneR_yA9xh-BWtDjU5I:bb6un1j) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L393)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

The original repo did not get any update in years ... I think we can safely diverge from it now :)
</blockquote></details>

Done
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java, line 438 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapPul02Rt20nFqiKQ:-MneRcv138UlnblYarGH:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/annotationreader/ApiConfigAnnotationReader.java#L438)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Ok, I will.  It will make it easier to add new validations like the one you suggested
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java, line 424 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-Mnar0W56GO0MFv9fCvR:-MneSa-T8qEOfO1NHmX0:bvon68d) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/discovery/DiscoveryGenerator.java#L424)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

The block could be shorter (and avoid repetitions) like this:

    ApiParameterBoundaries boundaries = parameterConfig.getBoundaries();
    if (boundaries != null) {
      Stream.of(boundaries.getDecimalMin(), boundaries.getMin())
              .findFirst().map(Objects::toString).ifPresent(schema::setMinimum);
      Stream.of(boundaries.getDecimalMax(), boundaries.getMax())
              .findFirst().map(Objects::toString).ifPresent(schema::setMaximum);
    }

Also, maybe a comment on how decimal bounds take precedence over integer ones?
</blockquote></details>

Nice (had to add a non null filter to avoid NPEs on findFirst)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 500 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnatR2p1P6SEd4sK3Vn:-MneT1rH518y-5JW9ByS:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L500)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

You can probably do something a bit nicer here too with Streams/Optionals, but it's a bit tricker
At least you can extract parameterConfig.getBoundaries() as a variable :-) (11 occurrences!!)

</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java, line 5 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/60#-MnapG5cCa7pmClSs3Gm:-MneRgFs66AQHASd_aU_:bmmuqvr) ([raw file](https://github.com/aodocs/endpoints-java/blob/0a6622ba3fd0d8812852a25775bb75c0df891a32/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiParameterBoundaries.java#L5)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

=> ApiParameterValidations
</blockquote></details>

ApiValidationConstraints in the end

**Review by clementdenis — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/60#-:-MneXdgvCiagfa-3FYem:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

**Pull request merged**
