### PR TITLE
[AOD-13307] Update to Java17

### PR DESCRIPTION
**Pull request by gmazak**
This change is [Reviewable](https://reviewable.io/reviews/AODocs/endpoints-java/74)

### CODE REVIEW

**Review by RaHery — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-java/74)* status: all files reviewed, 2 unresolved discussions (waiting on @gmazak)

___
*[`gradle.properties` line 1 at r1](https://reviewable.io/reviews/AODocs/endpoints-java/74#-NU_w9ew3Ngvos5N86o7:-NU_w9ew3Ngvos5N86o8:b-cknm0w) ([raw file](https://github.com/AODocs/endpoints-java/blob/01ad9b6c7fc26a9dee72a52dc8dbf402df3dd60d/gradle.properties#L1)):*
> ```INI
> version=2.6.0
> ```

We usually we remove the `SNAPSHOT` suffix when we do a release. Let's keep the suffix for now.
___
*[`discovery-client/build.gradle` line 28 at r1](https://reviewable.io/reviews/AODocs/endpoints-java/74#-NU_wUts6dvTBUDeqFVM:-NU_wUts6dvTBUDeqFVN:bc5xffb) ([raw file](https://github.com/AODocs/endpoints-java/blob/01ad9b6c7fc26a9dee72a52dc8dbf402df3dd60d/discovery-client/build.gradle#L28)):*
> ```Gradle
> targetCompatibility = 17
> jar.manifest.attributes("Built-By": "Google")
> jar.manifest.attributes("Build-Jdk": "1.8.x")
> ```

I am not sure about the meaning of this attribute, but shouldn't we change it as well?

**Review by gmazak — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-java/74)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[`gradle.properties` line 1 at r1](https://reviewable.io/reviews/AODocs/endpoints-java/74#-NU_w9ew3Ngvos5N86o7:-NUuNBUC4KtuHBjCvtne:b-896fix) ([raw file](https://github.com/AODocs/endpoints-java/blob/01ad9b6c7fc26a9dee72a52dc8dbf402df3dd60d/gradle.properties#L1)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

We usually we remove the `SNAPSHOT` suffix when we do a release. Let's keep the suffix for now.
</blockquote></details>

Done.
___
*[`discovery-client/build.gradle` line 28 at r1](https://reviewable.io/reviews/AODocs/endpoints-java/74#-NU_wUts6dvTBUDeqFVM:-NUuPiaO0jKS-7mSl5do:bl17o3u) ([raw file](https://github.com/AODocs/endpoints-java/blob/01ad9b6c7fc26a9dee72a52dc8dbf402df3dd60d/discovery-client/build.gradle#L28)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

I am not sure about the meaning of this attribute, but shouldn't we change it as well?
</blockquote></details>

Probably a custom attribute in the MANIFEST.MF.
I updated it, anyway.

**Comment by gmazak** [comment]
@RaHery Please don't merge it now: i need to add a JIRA number for the changes

**Comment by gmazak** [comment]
@RaHery Jira ticket number added.

**Review by RaHery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-java/74#-:-NV4iFeM94atp9L4Usj3:bnfp4nl)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @gmazak)

**Review by RaHery — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-java/74)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmazak)

**Pull request merged**
