### PR TITLE
Add an annotation value for the response status of a method

### PR DESCRIPTION
**Pull request by llbrt**
- add the annotation value responseStatus in ApiMethod
  to define a custom response status (other than 200
  204 if there is no content)
- add unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)

### CODE REVIEW

**Review by clementdenis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: 0 of 22 files reviewed, 1 unresolved discussion (waiting on @llbrt)

___
*[.travis.yml, line 1 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9baoKC8Sj7mjhOw6YR:-M9baoKC8Sj7mjhOw6YS:bfk3nxl) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/.travis.yml#L1)):*
> ```YAML
> dist: bionic
> ```

You should just remove the dist field to use latest one

**Review by alarribeau — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: all files reviewed, 5 unresolved discussions (waiting on @llbrt)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiMethod.java, line 73 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9be0Wa-u01BIjd_0x3:-M9be0Wa-u01BIjd_0x4:b-quja88) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiMethod.java#L73)):*
> ```Java
>    * The response status on success. If not set, the value is 200 or 204 if there is no content returned.
>    */
>   int responseStatus() default -1;
> ```

Isn't it possible to use the UNSET constant ? (maybe by moving it somewhere else if needed)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java, line 545 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bemsI3PSvs51dDRz0:-M9bemsI3PSvs51dDRz1:b-u801zn) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java#L545)):*
> ```Java
>   }
> 
>   public int getResponseStatus() {
> ```

responseStatus > customResponseStatus ?
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/config/validation/ApiConfigValidatorTest.java, line 508 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bgN-y2WM4tJ0QtRa8:-M9bg8Hx5Q5_kWi-81gX:b-zu2ye) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/test/java/com/google/api/server/spi/config/validation/ApiConfigValidatorTest.java#L508)):*
> ```Java
> 
>   @Test
>   public void testApiMethodConfigWithApiMethodResponseStatusInformal() throws Exception {
> ```

Using numbers would be clearer to me : 
testApiMethodConfigWithApiMethodResponseStatus1xx
(same remark for Redirection / 3xx)
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java, line 706 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bhHkO8vqOtqvNnsCD:-M9bhHkO8vqOtqvNnsCE:babt3os) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java#L706)):*
> ```Java
>     MockHttpServletResponse response = new MockHttpServletResponse();
>     ServletResponseResultWriter writer = getDefaultWriter(response);
>     writer.write(null, HttpServletResponse.SC_NO_CONTENT);
> ```

this test became a bit tautological
I'm thinking that you could have let the default status code logic in the write method by allowing -1 status : 
```
@Override
public void write(Object response, int status) throws IOException {
  if (status == -1) {
    status = (response == null) ? HttpServletResponse.SC_NO_CONTENT : SC_OK;
  }
  write(status, null, ResponseUtil.wrapCollection(response), false);
}
```
It would make this test more usefull.

**Review by llbrt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: 21 of 22 files reviewed, 4 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[.travis.yml, line 1 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9baoKC8Sj7mjhOw6YR:-M9brLX91hOFR6zmLoDr:brk1soq) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/.travis.yml#L1)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

You should just remove the dist field to use latest one
</blockquote></details>

Unfortunately, the default dist is not the most recent version of Ubuntu (and 20.04 fossa is not available yet) https://docs.travis-ci.com/user/reference/overview/#linux
So we must keep `dist: bionic`
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiMethod.java, line 73 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9be0Wa-u01BIjd_0x3:-M9btjGIC0t4QHCTPgb4:bkxlva) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/ApiMethod.java#L73)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Isn't it possible to use the UNSET constant ? (maybe by moving it somewhere else if needed)
</blockquote></details>

Yes, it works (though it wouldn't). So I renamed the value `RESPONSE_STATUS_UNSPECIFIED`, to keep the same wording (AuthLevel.UNSPECIFIED, ApiIssuerAudienceConfig.UNSPECIFIED, ...)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java, line 545 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bemsI3PSvs51dDRz0:-M9buILZEPB4j_JMSk-J:b-ccod6l) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java#L545)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

responseStatus > customResponseStatus ?
</blockquote></details>

I prefer to keep the usual bean convention: field xyz => getXyz() / setXyz()
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/config/validation/ApiConfigValidatorTest.java, line 508 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bgN-y2WM4tJ0QtRa8:-M9bvgdc2Mxkh8lXK_cL:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/test/java/com/google/api/server/spi/config/validation/ApiConfigValidatorTest.java#L508)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Using numbers would be clearer to me : 
testApiMethodConfigWithApiMethodResponseStatus1xx
(same remark for Redirection / 3xx)
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java, line 706 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bhHkO8vqOtqvNnsCD:-M9bx_5K7_hITedMSKHo:b-i8fc1z) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java#L706)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

this test became a bit tautological
I'm thinking that you could have let the default status code logic in the write method by allowing -1 status : 
```
@Override
public void write(Object response, int status) throws IOException {
  if (status == -1) {
    status = (response == null) ? HttpServletResponse.SC_NO_CONTENT : SC_OK;
  }
  write(status, null, ResponseUtil.wrapCollection(response), false);
}
```
It would make this test more usefull.
</blockquote></details>

Previously, the writer was 'smart' on the status AND on the response; this test was testing both the status and the response in the case of an empty response.

Now, the writer just writes the given status, but we still need to test the handling of the response. That's why I kept this test and put a 'plausible' status.
We may remove the assert on the status if it's too tautological.

**Review by clementdenis — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: 17 of 22 files reviewed, 4 unresolved discussions (waiting on @alarribeau and @llbrt)

___
*[.travis.yml, line 1 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9baoKC8Sj7mjhOw6YR:-M9c4M4ODvJXqhm1wRPG:b-bcdeq9) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/.travis.yml#L1)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

Unfortunately, the default dist is not the most recent version of Ubuntu (and 20.04 fossa is not available yet) https://docs.travis-ci.com/user/reference/overview/#linux
So we must keep `dist: bionic`
</blockquote></details>

I meant the most recent distribution available on Travis

**Review by alarribeau — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: 19 of 22 files reviewed, 2 unresolved discussions (waiting on @alarribeau and @llbrt)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java, line 545 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bemsI3PSvs51dDRz0:-M9c9rXh8kwliam_yEAh:b-3059k7) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java#L545)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

I prefer to keep the usual bean convention: field xyz => getXyz() / setXyz()
</blockquote></details>

My point wasn't to remove the get/set prefixes but to rename the field (and getters/setters) by adding the **custom** prefix (like you did with **effective**).
(I should have added my comment on the field instead)

**Review by alarribeau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: all files reviewed, 2 unresolved discussions (waiting on @llbrt)

**Review by llbrt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: all files reviewed, 2 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java, line 545 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bemsI3PSvs51dDRz0:-M9cPVH57t1ondvtutxf:b-sy2f93) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java#L545)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

My point wasn't to remove the get/set prefixes but to rename the field (and getters/setters) by adding the **custom** prefix (like you did with **effective**).
(I should have added my comment on the field instead)
</blockquote></details>

Yes, I know, but I'm not in favor of adding 'custom'.

- In ApiMethodConfig, the fields have the same name as the fields in the annotation ApiMethod (httpMethod, authenticators, ...). So the field name must be responseStatus, not customResponseStatus
- there are getters and setters for each field that follow the bean naming rule (set/getHttpMethod, set/getAuthenticators, ...)
- unfortunately, this new responseStatus has 2 possible default values, depending on another field. So, we cannot set a 'real' default value and we need to get both what is defined (or not) by the user and what must be set in the response (the effective value).

Adding 'custom' to the field or only to the 'bean' getter/setter doesn't add any value for the comprehension of the code (in fact, I find it more confusing) and doesn't follow the naming rules of the class.

We may find a better naming for 'getEffectiveResponseStatus()', but we must keep getResponseStatus() and setResponseStatus().

**Review by llbrt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: all files reviewed, 2 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[.travis.yml, line 1 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9baoKC8Sj7mjhOw6YR:-M9cWnj66gr6aeJH0y33:b4putsz) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/.travis.yml#L1)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I meant the most recent distribution available on Travis
</blockquote></details>

:ok_hand:

**Review by clementdenis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau)

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/54#-:-M9cj9x20Dkn8bkKyIt6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java, line 545 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/54#-M9bemsI3PSvs51dDRz0:-M9cirmU86FlZ-b5V5eg:b-dz6ntg) ([raw file](https://github.com/aodocs/endpoints-java/blob/d7f653584ded6cff0a709f8febdf9031856db5a5/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiMethodConfig.java#L545)):*
Ok, I didn't had this in mind : 
> In ApiMethodConfig, the fields have the same name as the fields in the annotation ApiMethod (httpMethod, authenticators, ...). So the field name must be responseStatus, not customResponseStatus

**Pull request merged**
