### PR TITLE
Allow redirect by api method

### PR DESCRIPTION
**Pull request by llbrt**
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55)

### CODE REVIEW

**Review by alarribeau — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55)* status: all files reviewed, 4 unresolved discussions (waiting on @llbrt)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/response/RedirectException.java, line 11 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDtums83YotJYvkH6r:-MPDtums83YotJYvkH6s:b-dzqo5i) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/main/java/com/google/api/server/spi/response/RedirectException.java#L11)):*
> ```Java
> /**
>  * Exception that is mapped to a redirection to the given location.
>  * The status must be a 3xx redirect code.
> ```

I would add some usage recommendation like : 
```
exception to be thrown by endpoint methods for returning a redirection response instead of the declared response payload.
```
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java, line 297 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDrNvqC7_RutLbUHK6:-MPDrNvqC7_RutLbUHK7:b-8kr63z) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java#L297)):*
> ```Java
>     RestServletRequestParamReader reader = createReader(ImmutableMap.of("path", "1234"));
> 
>     BadRequestException e = Assert.assertThrows(BadRequestException.class, reader::read);
> ```

IMO the use of method reference makes it harder to spot the tested statement.
vs a dedicated line : 
```
BadRequestException e = Assert.assertThrows(BadRequestException.class, () ->
    reader.read()
);
```
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/response/RedirectExceptionTest.java, line 23 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDs7ZO0_JQN1_6iGQ2:-MPDs7ZO0_JQN1_6iGQ3:bxveekn) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/test/java/com/google/api/server/spi/response/RedirectExceptionTest.java#L23)):*
> ```Java
>   @Test
>   public void statusBadRequest_fails() {
>     Assert.assertThrows(IllegalArgumentException.class, () -> new RedirectException(400, "message", "location"));
> ```

(I would also test boundaries)
___
*[endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/LocalClientLibGeneratorTest.java, line 94 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDsL_9C9YTSQGojB-W:-MPDsL_9C9YTSQGojB-X:bbe2bmp) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/LocalClientLibGeneratorTest.java#L94)):*
> ```Java
>     discoveryDoc = IoUtil.readStream(FakeClientLibGenerator.class.getResourceAsStream("fake-api-config.json"));
>     File destinationDir = tmpFolder.newFolder("destination");
>     Assert.assertThrows(IOException.class, () -> generator.generateClientLib(discoveryDoc, "java", null, null, destinationDir));
> ```

(same remark in this class)

**Review by RaHery — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55#-:-MPE4MzsCirEq8g2vhIZ:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @llbrt)

**Review by llbrt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/response/RedirectException.java, line 11 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDtums83YotJYvkH6r:-MPDzpJkAcWHdXPwgkdH:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/main/java/com/google/api/server/spi/response/RedirectException.java#L11)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

I would add some usage recommendation like : 
```
exception to be thrown by endpoint methods for returning a redirection response instead of the declared response payload.
```
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java, line 297 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDrNvqC7_RutLbUHK6:-MPE-IJw-48AK2YCH_iu:bqacnq4) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java#L297)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

IMO the use of method reference makes it harder to spot the tested statement.
vs a dedicated line : 
```
BadRequestException e = Assert.assertThrows(BadRequestException.class, () ->
    reader.read()
);
```
</blockquote></details>

Done, but Intellij doesn't like that :see_no_evil:  (`Lambda can be replaced with method reference`)
___
*[endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/LocalClientLibGeneratorTest.java, line 94 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDsL_9C9YTSQGojB-W:-MPE4AF32VF22HxXbXHZ:bb6un1j) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework-tools/src/test/java/com/google/api/server/spi/tools/LocalClientLibGeneratorTest.java#L94)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

(same remark in this class)
</blockquote></details>

Done

**Review by alarribeau — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @llbrt)

___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java, line 297 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/55#-MPDrNvqC7_RutLbUHK6:-MPEgsBDBB-dMTTVEOtM:b-mk5m31) ([raw file](https://github.com/aodocs/endpoints-java/blob/0dd3cf65e407033275a0c3576a1d1a45ee4b24fa/endpoints-framework/src/test/java/com/google/api/server/spi/request/RestServletRequestParamReaderTest.java#L297)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

Done, but Intellij doesn't like that :see_no_evil:  (`Lambda can be replaced with method reference`)
</blockquote></details>

If this bothers you too much you can keep the method reference but skip a line to highlight the tested statement

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55#-:-MPEhJXy4drNxB1zrGBw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @llbrt)

**Review by RaHery — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @llbrt)

**Pull request merged**
