### PR TITLE
Use standard object writer for errors

### PR DESCRIPTION
**Pull request by clementdenis**

### CODE REVIEW

**Review by RaHery — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau, @clementdenis, and @llbrt)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/response/ServletResponseResultWriter.java, line 96 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/24#-Lho9eAs0H5aolSor_Wb:-Lho9eAtEJT0ams5ofp1:b-rmttb8) ([raw file](https://github.com/aodocs/endpoints-java/blob/09f5089693b997891a906b4ba61ba73c5718f887/endpoints-framework/src/main/java/com/google/api/server/spi/response/ServletResponseResultWriter.java#L96)):*
> ```Java
>     }
>     this.objectWriter = configureWriter(objectWriter);
>     this.errorObjectWriter = objectWriter;
> ```

The method `configureObject(..)` is not a pure function: it may change the state of the input parameter `objectWriter`. If it does, the `errorObjectWriter` would inherit the side effect of this change.
It would be safer to assign a different object to `errorObjectWriter` instead of reusing the same instance.

**Comment by clementdenis** [comment]
From [the ObjectWriter Javadoc](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/ObjectWriter.html):

> new instances are constructed for different configurations

So com.fasterxml.jackson.databind.ObjectWriter instances are effectively immutable, their state can't be changed, so the logic here should be OK.

**Review by RaHery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/24#-:-LhoeOny5IdR4OD2Nh-G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau, @clementdenis, and @llbrt)

**Review by llbrt — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/24#-:-Lhon3X2Efj-w7XuxmTO:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau, @clementdenis, and @llbrt)

**Review by llbrt — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/24)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau and @clementdenis)

**Review by RaHery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

**Pull request merged**
