### PR TITLE
Improve generated Swagger spec compatibility with Endpoints Portal

### PR DESCRIPTION
**Pull request by clementdenis**
* Support Endpoints Portal authorization flow
- Add authorizationUrl and useScopesInAuthFlow issuer config params
- Define default authorizationUrl for Google id token issuers
- Add scopes in operation's security (required for Try it! in Portal)
- Add authorizationUrl in OAuth2 flow (required for Try it! in Portal)
- Reorder Google id token issuers to have https:// one first
* New supported Swagger features
- Support deprecation on Swagger operations with @Deprecated
- Add tags to Swagger operations to group like API Explorer in Portal
- Inline Map types (including JsonMap) to avoid useless definitions
- Set default values for parameters
- Add proper collection format (multi instead of csv)
- List unsupported features of the spec in UNSUPPORTED_FEATURES.md
* Order consistency
- Remove ordering attempt in reflection-based introspection
- Add ordering in Swagger generation (sort paths by string order)
* Testing
- Improve coverage of SwaggerGenerator (array tests)
- Extract Swagger assertion logic in a truth.dev subject
- Update truth.dev to 1.0
* Cleanup
- Remove writeInternal boolean in SwaggerGenerator (not used)

### CODE REVIEW

**Review by alarribeau — APPROVED** [review]
It looks ok but to be honest I can't assure it. Let's merge and see :)
(It could have been splited in various PRs and/or commits. For remaining swagger features, if we do support them, I suggest to create 1 PR by feature).

**Review by RaHery — COMMENTED** [review]
+1

> Reviewed 1 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34#-:-Ll6F5Xa9amn1yftJW3A:b32v57)* status: 1 of 40 files reviewed, all discussions resolved (waiting on @llbrt and @RaHery)

**Review by RaHery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34#-:-Ll6FC2t3gFBdrmpKKGJ:bnfp4nl)* status: 1 of 40 files reviewed, all discussions resolved (waiting on @llbrt and @RaHery)

**Review by RaHery — APPROVED** [review]
> Reviewed 39 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @llbrt)

**Review by llbrt — APPROVED** [review]
idem, :lgtm: 

> Reviewed 40 of 40 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34#-:-Ll7_8-c-hEZ_w9bE5bZ:broduhk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by llbrt — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34#-:-Ll7_j0XEQUMhi5QBAmJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by RaHery — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
