### PR TITLE
Fix handling of empty strings in maps (should be included in response by default)

### PR DESCRIPTION
**Pull request by clementdenis**
- Allow "custom" ConfiguredObjectMapper
- Add many test cases for Strings in containers

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/50)

### CODE REVIEW

**Review by llbrt — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/50)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java, line 225 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/50#-Lub9XtG3YoZU7FUT2zl:-Lub9XtH4LBHiaguwJ55:bdssp5l) ([raw file](https://github.com/aodocs/endpoints-java/blob/c23ae6592c5dfd81198f6c3028bdb3d451f96334/endpoints-framework/src/test/java/com/google/api/server/spi/response/ServletResponseResultWriterTest.java#L225)):*
> ```
> Mapepr
> ```
Mapper

**Review by alarribeau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/50)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/50#-:-LubKhFu9mprSUJxXxbZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/50)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

**Pull request merged**
