### PR TITLE
Use proper ServiceException when impossible to parse json input.

### PR DESCRIPTION
**Pull request by RaHery**
- Strip out all information about internal implementation in the error message.
- for AOD-8242

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/30)

### CODE REVIEW

**Review by alarribeau — APPROVED** [review]

**Review by llbrt — APPROVED** [review]
Maybe you should remove extra spaces in empty lines (none present in original code).

:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/30#-:-LjQIjEr14IXhaNj2qDy:b-8c4llc)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis)

**Review by alarribeau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/30)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis)

**Review by clementdenis — COMMENTED** [review]
I don't see any support (or test) for the errors of type JsonProcessingException (item 2 in AOD-8242)
Do you plan to implement this separately, or was it forgotten?

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/30#-:-Ljz7CHr9Av6kqeCwUDl:b-rrk2ft)* status: all files reviewed, 3 unresolved discussions (waiting on @RaHery)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 172 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz4eXG53wkZV-uLVMV:-Ljz4eXG53wkZV-uLVMW:bqzd8he) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L172)):*
> ```Java
>         | IOException e) {
>       logger.atInfo().withCause(e).log("Unable to read request parameter(s)");
>       throw new BadRequestException("Parse error", "parseError", "global");
> ```

I think it's still worth to propagate the error as the cause of the BadRequestException.
Also, there's no need for the "global" domain, it's the default value if not set.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 202 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz4-cl32n6GGDKID1G:-Ljz4-cl32n6GGDKID1H:b-75v637) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L202)):*
> ```Java
>       );
>     } else {
>       return new BadRequestException("Parse error", reason, "global");
> ```

I would rather store the message in a variable and have a single BadRequestException created and returned at the end.
And I would also propagate the cause.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 222 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz68Nd56HvcgufjUA1:-Ljz68Nd56HvcgufjUA2:bdhj99k) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L222)):*
> ```Java
>             || float.class.equals(clazz)
>             || double.class.equals(clazz);
>   }
> ```

The type checks should use FieldType and its fromType() method instead to keep the logic centralized.

**Review by RaHery — COMMENTED** [review]
JsonParseException and JsonEOFException are both IOException. Those exception, and any other exception related to the parsing that are IOException, are properly caught and message is just `Parse error`. 
I added a test case to exhibit this feature.

Since this PR was already merged, i'll create another one with all of the modifications.

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/30#-:-Lk41RUx-GGTBJ34Z3_J:b190jvg)* status: all files reviewed, 3 unresolved discussions (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 172 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz4eXG53wkZV-uLVMV:-Lk41lT7AawBYlySUB-w:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L172)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I think it's still worth to propagate the error as the cause of the BadRequestException.
Also, there's no need for the "global" domain, it's the default value if not set.
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 202 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz4-cl32n6GGDKID1G:-Lk41mkUEVWFOl4jHn0A:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L202)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I would rather store the message in a variable and have a single BadRequestException created and returned at the end.
And I would also propagate the cause.
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 222 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/30#-Ljz68Nd56HvcgufjUA1:-Lk41o8w2ebeAge3_Ifm:b-q8vywc) ([raw file](https://github.com/aodocs/endpoints-java/blob/596e35bade214b3166eb65d83a06e88e4f221f3e/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L222)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

The type checks should use FieldType and its fromType() method instead to keep the logic centralized.
</blockquote></details>

The logic are not the same. 
There are similarities in the implementation, but the output is not the same, in value and semantically. The only thing in common is the type of input (Class) and the output (String). I think it's not worth it to factor those two pieces of code.

**Pull request merged**
