### PR TITLE
Request content-type validation

### PR DESCRIPTION
**Pull request by alarribeau**
The validation must be enabled by a new servlet parameter 'enableContentTypeValidation'.

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62)

### CODE REVIEW

**Review by clementdenis — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62)* status: all files reviewed, 1 unresolved discussion (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 179 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/62#-Momhz6379Dr2Y3iGvYQ:-Momhz6379Dr2Y3iGvYR:b-iw322d) ([raw file](https://github.com/aodocs/endpoints-java/blob/acc8c893f6f7b1581a942bb5cee30f062b304c67/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L179)):*
> ```Java
>     }
>     String contentType = httpServletRequest.getContentType();
>     if (Objects.isNull(contentType) || !contentType.contains("application/json")) {
> ```

Shoulnd't it be startsWith instead of contains?

Or you could go further and use MediaType from Guava:
    
    MediaType.parse(contentType).is(MediaType.parse("application/json"))

=> this will accept any JSON content type, regardless of the charset

**Review by alarribeau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 179 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/62#-Momhz6379Dr2Y3iGvYQ:-MonRlAl5HgtgnXgDdM3:bve6obx) ([raw file](https://github.com/aodocs/endpoints-java/blob/acc8c893f6f7b1581a942bb5cee30f062b304c67/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L179)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Shoulnd't it be startsWith instead of contains?

Or you could go further and use MediaType from Guava:
    
    MediaType.parse(contentType).is(MediaType.parse("application/json"))

=> this will accept any JSON content type, regardless of the charset
</blockquote></details>

I think startsWith would be more efficient and avoid any parsing error. Is it ok for you ?

**Review by clementdenis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 179 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/62#-Momhz6379Dr2Y3iGvYQ:-MonTx9u3lIY1oFUx0xh:b65h4o6) ([raw file](https://github.com/aodocs/endpoints-java/blob/acc8c893f6f7b1581a942bb5cee30f062b304c67/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L179)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

I think startsWith would be more efficient and avoid any parsing error. Is it ok for you ?
</blockquote></details>

Yes, that's good for me!

**Review by alarribeau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java, line 179 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/62#-Momhz6379Dr2Y3iGvYQ:-MonhZ6n6lyednsswGoX:bb6un1j) ([raw file](https://github.com/aodocs/endpoints-java/blob/acc8c893f6f7b1581a942bb5cee30f062b304c67/endpoints-framework/src/main/java/com/google/api/server/spi/request/RestServletRequestParamReader.java#L179)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Yes, that's good for me!
</blockquote></details>

Done

**Review by clementdenis — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/62#-:-Mp65kRzB1facyLTslt_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

**Pull request merged**
