### PR TITLE
Fix client generation on Windows

### PR DESCRIPTION
**Pull request by Botffy**
Due to https://bugs.python.org/issue9148 the generate_library.exe
started by LocalClientLibGenerator always returned 0 immediately after
being started, with the actual library generation taking place
asynchronously. Since we have already deleted the discovery file by the
time the Python process reached it, the library generation always failed
on Windows.

This commit provides a workaround by allowing the user to specify two environmental
variables:

- GOOGLE_GENERATE_LIBRARY_PYTHON should contain the user's Python2
executable (defaults to 'python'
- GOOGLE_GENERATE_LIBRARY_SCRIPT_LOCATION should point at the user's
generate_library.py (defaults to
{user.home}\\AppData\Roaming\Python\Python27\site-packages\googleapis\codegen\generate_library.py)

---
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/70)

### CODE REVIEW

**Review by RaHery — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/70#-:-Mz0AP418ZmX9Aa2zupB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Botffy)

**Review by RaHery — CHANGES_REQUESTED** [review]
fyi, this build has introduced a new "issue" in code quality verification: https://codebeat.co/projects/github-com-aodocs-endpoints-java-master/pull_requests/567224

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/70#-:-Mz0EKSH6WeiGJUMGYyC:bjpcico)* status: all files reviewed, 1 unresolved discussion (waiting on @Botffy)

___
*[endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/LocalClientLibGenerator.java, line 117 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/70#-Mz0DS5Y7E1Bsje7A5Dh:-Mz0DS5Y7E1Bsje7A5Di:b7icnxy) ([raw file](https://github.com/aodocs/endpoints-java/blob/c9e81a6e35b76cc2443c5fee579cf9a803e40311/endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/LocalClientLibGenerator.java#L117)):*
> ```Java
>       
>       String scriptLocation = System.getenv("GOOGLE_GENERATE_LIBRARY_SCRIPT_LOCATION");
>       if (!Strings.isEmptyOrWhitespace(scriptLocation)) {
> ```

Shouldn't you also check here that the files pointed by `scriptLocation` exists? And even maybe go further and check that the name of the file is `generate_library.py`

**Review by Botffy — COMMENTED** [review]
Refactored it, hopefully it'll like it better this way

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/70#-:-Mz0XZl1--x8rYANlhFF:b-8ogp0e)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RaHery)

___
*[endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/LocalClientLibGenerator.java, line 117 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/70#-Mz0DS5Y7E1Bsje7A5Dh:-Mz0Xe7t-bAH55yKE2YQ:b-896fja) ([raw file](https://github.com/aodocs/endpoints-java/blob/c9e81a6e35b76cc2443c5fee579cf9a803e40311/endpoints-framework-tools/src/main/java/com/google/api/server/spi/tools/LocalClientLibGenerator.java#L117)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Shouldn't you also check here that the files pointed by `scriptLocation` exists? And even maybe go further and check that the name of the file is `generate_library.py`
</blockquote></details>

Done!

**Review by RaHery — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/70)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Botffy)

**Pull request merged**
