### PR TITLE
Add scope in security definitions (current spec is not valid)

### PR DESCRIPTION
**Pull request by clementdenis**
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/36)

### CODE REVIEW

**Review by llbrt — APPROVED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/36)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 646 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/36#-Lm3zRdQDjcBadixBPv2:-Lm3zRdQDjcBadixBPv3:beb5hhi) ([raw file](https://github.com/aodocs/endpoints-java/blob/d2095f9d584d430a04cf4345d6928bd66f6b588c/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L646)):*
> ```
> propertiesMatchExceptScope
> ```
May add a unit test where propertiesMatchExceptScope is false

**Review by clementdenis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/36)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 646 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/36#-Lm3zRdQDjcBadixBPv2:-Lm41pW8CsQIPpOy2AgF:bnh8ktc) ([raw file](https://github.com/aodocs/endpoints-java/blob/d2095f9d584d430a04cf4345d6928bd66f6b588c/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L646)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

> ```
> propertiesMatchExceptScope
> ```
May add a unit test where propertiesMatchExceptScope is false
</blockquote></details>

I don't think it's actually possible to create this situation (at least I don't know how to).
I just have two paths that throw exceptions instead of one previously because the check is more precise.
The previously thrown ApiConfigException was not unit tested either for the same reason: the case (probably) cannot happen.

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/36)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java, line 646 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/36#-Lm3zRdQDjcBadixBPv2:-Lm4ASUL2iScEZkUB-o0:b4putsz) ([raw file](https://github.com/aodocs/endpoints-java/blob/d2095f9d584d430a04cf4345d6928bd66f6b588c/endpoints-framework/src/main/java/com/google/api/server/spi/swagger/SwaggerGenerator.java#L646)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I don't think it's actually possible to create this situation (at least I don't know how to).
I just have two paths that throw exceptions instead of one previously because the check is more precise.
The previously thrown ApiConfigException was not unit tested either for the same reason: the case (probably) cannot happen.
</blockquote></details>

:ok_hand:

**Review by llbrt — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/36#-:-Lm4ApVEB8HXuQVrFdB4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
