### PR TITLE
Populate resource field validation attributes in Swagger and Discovery

### PR DESCRIPTION
**Pull request by alarribeau**
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/63)

### CODE REVIEW

**Review by clementdenis — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/63)* status: all files reviewed, 2 unresolved discussions (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java, line 83 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/63#-MpMUOP787rru6dEKjI7:-MpMUOP8Cs6yRpVfUWm-:b-3aax3p) ([raw file](https://github.com/aodocs/endpoints-java/blob/45257df3efa57d00a732a22e233db0b8a73c31e2/endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java#L83)):*
> ```Java
>     this.typeLoader = new TypeLoader(JsonConfigWriter.class.getClassLoader());
>     this.validator = new ApiConfigValidator(typeLoader, new SchemaRepository(typeLoader));
>     this.resourceSchemaProvider = new JacksonResourceSchemaProvider(typeLoader);
> ```

Would be better to call the other other constructor
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiValidationConstraints.java, line 78 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/63#-MpMUbSJ34dwmoz1cKEO:-MpMUbSJ34dwmoz1cKEP:b-e5lcr5) ([raw file](https://github.com/aodocs/endpoints-java/blob/45257df3efa57d00a732a22e233db0b8a73c31e2/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiValidationConstraints.java#L78)):*
> ```Java
> 	public boolean isEmpty() {
> 		return !Stream.of(pattern, min, max, decimalMin, decimalMax, decimalMinInclusive, decimalMaxInclusive, minSize, maxSize)
> 				.anyMatch(Objects::nonNull);
> ```

Would be simpler with Stream.of(...).allMatch(Objects::null)

**Review by alarribeau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/63)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @clementdenis)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java, line 83 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/63#-MpMUOP787rru6dEKjI7:-MpMrxVS-_dqcrso8A_y:bn75t6b) ([raw file](https://github.com/aodocs/endpoints-java/blob/45257df3efa57d00a732a22e233db0b8a73c31e2/endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java#L83)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Would be better to call the other other constructor
</blockquote></details>

I wanted to do this but I dont know how to do it while still reusing the same type loader (cause this() must be the first statement). 
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiValidationConstraints.java, line 78 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/63#-MpMUbSJ34dwmoz1cKEO:-MpMuESz2tIPhUnjGXLs:b-3cslex) ([raw file](https://github.com/aodocs/endpoints-java/blob/45257df3efa57d00a732a22e233db0b8a73c31e2/endpoints-framework/src/main/java/com/google/api/server/spi/config/model/ApiValidationConstraints.java#L78)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Would be simpler with Stream.of(...).allMatch(Objects::null)
</blockquote></details>

indeed!

**Review by clementdenis — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/63)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @alarribeau)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java, line 83 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/63#-MpMUOP787rru6dEKjI7:-MpNFv824c6lJowYbCKX:biz3b2m) ([raw file](https://github.com/aodocs/endpoints-java/blob/45257df3efa57d00a732a22e233db0b8a73c31e2/endpoints-framework/src/main/java/com/google/api/server/spi/config/jsonwriter/JsonConfigWriter.java#L83)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

I wanted to do this but I dont know how to do it while still reusing the same type loader (cause this() must be the first statement). 
</blockquote></details>

You would need another constructor indeed:

      public JsonConfigWriter() throws ClassNotFoundException {
        this(new TypeLoader(JsonConfigWriter.class.getClassLoader()));
      }
      
      private JsonConfigWriter(TypeLoader typeLoader)  {
        this(typeLoader, new ApiConfigValidator(typeLoader, new SchemaRepository(typeLoader)));
      }

=> not worth it

**Review by clementdenis — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/63)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)

**Pull request merged**
