### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by RaHery**
This change is [Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/28)

### CODE REVIEW

**Review by llbrt — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/28#-:-LiHuy2tEVB2O6TXu5te:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by alarribeau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/28#-:-LiHvVbSDsWpG86e78k-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by alarribeau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by llbrt — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/28)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
