### PR TITLE
Fix inconsistent enum constant names between schema and serialization

### PR DESCRIPTION
**Pull request by clementdenis**
- param and resource de/serialization uses Jackson configuration
- schema generation used Enum.name(), should use Jackson instead

### CODE REVIEW

**Review by alarribeau — APPROVED** [review]
Cool !

**Review by llbrt — APPROVED** [review]
Great! May return an unmodifiable map, but would be a bit overkill...

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/15#-:-L_8d3KK2ed9CqBwVT0Q:b-difx9z)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Review by llbrt — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/15#-:-L_8dgMr6aLuVZpXEgHb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Review by alarribeau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Review by RaHery — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/15#-:-LaPPc9k-3BRv4SClx7X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaHery)

**Pull request merged**
